version: '3.8'
services:
  api:
    image: reserv/worldline-rsv-digital-wl-backend
    container_name: "digital_wl_backend_test"
    restart: unless-stopped
    ports:
      - 9087:9083
    volumes:
      - "./images/:/opt/digitalizacion/images/:z"
      - "./configuracion/:/opt/digitalizacion/configuracion/:z"
    environment:
      - SPRING_PROFILES_ACTIVE=testing
    networks:
      - db_net
      - default

#volumes:
#  vol_imagenes:

networks:
  db_net:
    external: true
    name: postgrestest_net