concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "build"
  url = "https://domain.com.ar"
  id = 6
  token = "glrt-Spbw5poc4N2E-jrXYGfz"
  token_obtained_at = 2023-08-01T22:01:23Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "instance"

[[runners]]
  name = "build"
  url = "https://domain.com.ar"
  id = 7
  token = "glrt-32jeD2_ftQ7xeh2APexV"
  token_obtained_at = 2023-08-01T22:03:25Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "instance"

[[runners]]
  name = "build"
  url = "https://domain.com.ar"
  id = 8
  token = "glrt-VqJ-waXinsXiYsKxFcrb"
  token_obtained_at = 2023-08-02T02:43:32Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0

[[runners]]
  name = "docker"
  url = "https://domain.com.ar"
  id = 9
  token = "glrt-tqZvdgLXyX-V5G4uFF4_"
  token_obtained_at = 2023-08-02T18:59:36Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "docker:dind"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0