version: '3.8'
services:
    gitlab:
      image: 'gitlab/gitlab-ce:latest'
      restart: unless-stopped
      hostname: gitlab.domain.com.ar
      mem_limit: '5g'
      cpus: '3'
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'https://gitlab.domain.com.ar'
          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = "smtp.gmail.com"
          gitlab_rails['smtp_port'] = 587
          gitlab_rails['smtp_user_name'] = "mail@gmail.com"
          gitlab_rails['smtp_password'] = "pw"
          gitlab_rails['smtp_domain'] = "smtp.gmail.com"
          gitlab_rails['smtp_authentication'] = "login"
          gitlab_rails['smtp_enable_starttls_auto'] = true
          gitlab_rails['smtp_tls'] = false
          gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
          gitlab_rails['gitlab_shell_ssh_port'] = 8022
        # Add any other gitlab.rb configuration here, each on its own line
      ports:
        - '8080:80'
        - '8443:443'
        - '8022:22'
      volumes:
        - "./config:/etc/gitlab:Z"
        - "./logs:/var/log/gitlab:Z"
        - "./data:/var/opt/gitlab:Z"
