version: '3.8'
services:
  db:
    image: mariadb:10.8
    restart: unless-stopped
    ports:
      - 23306:3306
    volumes:
      - "dbc:/var/lib/mysql:cached"
    environment:
      - MYSQL_ROOT_PASSWORD=pwroot
      - TZ=America/Argentina/Buenos_Aires
    networks:
      - db_net
    mem_limit: '1g'
    cpus: '1'

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 10812:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=pwroot
      - PMA_ABSOLUTE_URI=https://domain.com.ar/
      - UPLOAD_LIMIT=8G
    depends_on:
      - db
    networks:
      - db_net
    mem_limit: '1g'
    cpus: '1'
volumes:
  dbc:

networks:
  db_net:
    name: mysqltest_net
